version: '3'

services:

  postgres-dev:
    image: postgres:11
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demodb
    ports:
      - 5432:5432
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data

  admin:
      image: adminer
      ports:
        - 8080:8080
      depends_on:
        - postgres-dev